---
- hosts: preprod
  remote_user: root

  gather_facts: false
  pre_tasks:
  - name: Install python for Ansible if not available
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python2.7 python-minimal)
    changed_when: false
  - setup: # aka gather_facts

  roles:
  - firewall
  - pubkeys
  - docker
  - timezone
 
  tasks:
  - name: rsync files
    synchronize: src={{item.src}} dest={{item.dest}} recursive='yes'
    with_items:
    - { src: 'docker-compose.yml', dest: '/gitea-drone/' }
    - { src: 'gitea-app.ini', dest: '/gitea-drone/' }
    - { src: 'traefik/prod', dest: '/gitea-drone/traefik/' }

  - name: stop all
    shell: cd /gitea-drone && docker-compose down

  - name: delete network
    shell: docker network rm gitea-network || echo "Network does not exist"

  - name: recreate network
    shell: docker network create gitea-network || echo "Can't create docker network, already created ?"
  
  - name: run
    shell: cd /gitea-drone && docker-compose up -d
